@extends('layout.main')

@section('content')
    <div>
        <h1>Contatti</h1>
        <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate expedita molestias quam obcaecati libero assumenda fugiat inventore sed dolor asperiores maiores eligendi, porro consectetur quisquam labore repudiandae neque sequi quaerat laudantium id! Aut quisquam architecto eos sunt ut dicta debitis illo id. Doloribus, repudiandae deleniti esse vel quod quas laboriosam nobis. Voluptatum reiciendis delectus, omnis quo perferendis sit fuga provident fugit a architecto est et quis, iste distinctio, maxime iure accusamus at? Corporis aliquam possimus voluptate ratione magni quos illo expedita necessitatibus, in incidunt quidem eum voluptatem quia animi aut quisquam quaerat doloremque pariatur error neque vero earum harum iure? Assumenda ratione animi saepe esse, expedita incidunt dolorem fuga est illo? Consequuntur magni illum dolore repellat blanditiis ullam reprehenderit earum, deleniti, aut quibusdam voluptate reiciendis perspiciatis nihil tempore dolores! Excepturi, cupiditate inventore quia dolores labore quisquam harum magnam nihil velit assumenda adipisci quidem in, est unde sit nemo voluptatibus quis sint veniam quibusdam rerum aut! Id animi fugit quae nemo corporis hic dolore fugiat sequi vero enim! Quidem neque iusto id possimus in, vero labore alias voluptatem aspernatur dolore ducimus ut nam repellat libero aliquam eveniet. Maxime assumenda porro eos ipsam deleniti, officiis, veritatis eligendi perferendis iusto tenetur tempore labore. Architecto sed autem pariatur amet voluptates magni consectetur aut assumenda commodi harum! Veritatis minima maiores inventore laborum nisi autem minus totam, exercitationem saepe earum dicta praesentium blanditiis. Perspiciatis earum fugit architecto non. Ex voluptas fugit, dolore facere obcaecati laborum architecto hic eveniet quaerat repudiandae dolorum voluptate quis corrupti, unde deleniti officia quibusdam nisi. Nostrum ab est velit atque deleniti perspiciatis earum illum repudiandae architecto voluptatem, saepe excepturi eligendi officia magni optio explicabo repellat. Dolor labore molestias adipisci magnam, natus dolores praesentium ea nam sunt deserunt ab! Fugit voluptatum dolorum, quisquam dolores vitae placeat minima ipsa, ipsam hic libero quidem iure.
        </p>
    </div>
@endsection
